let number = 5;
if (number > 0){
    // code to execute 
    console.log("The number is postive")
}





let age = 18;
if (age >=18){
    // code to execute
    console.log("The person is eligible to vote")
}


let temp =25;
if (temp >30){
    // code to execute
    console.log("Its hot")
}else if( temp >=20 && temp<=30){
    console.log("Its moderate")
}else {
    console.log("Its cold")
}


// check if a number is pos , neg , zero
let expired=false;
let quality=7
if (expired==true){
console.log("Do not use")
}
if (expired==false){
    if (quality>=8){
        console.log("Good quality")
    }
    else if (quality>=5 && quality<=8){
        console.log("Average quality")
     }
    else {
        console.log("Poor quality")
    } 

}