//Num 1
 ///Function that texts my name en greets in luganda
 function  named(Angellah){
    console.log('gyebaleko',Angellah)
    
     }
     named('Angellah')

     






   ///NUM2
function profit_calculation(cost_price,selling_price,unit_price){
    var cost_price = 100;
    var selling_price = 23;
    var unit_price = 32;
    var profit = selling_price - cost_price;
    console.log("profit",profit);
    return profit;
    }
    profit_calculation();
    
    



 
  // Num 3
  
  let num1 = 15;
  let num2 = 4;
  
  let result = calculate(num1, num2, "+");
  console.log(result); 
  
  result = calculate(num1, num2, "-");
  console.log(result); 
  
  result = calculate(num1, num2, "*");
  console.log(result); 
  
  result = calculate(num1, num2, "/");
  console.log(result);
     